/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hao_NDKDemoActivity */

#ifndef _Included_com_hao_NDKDemoActivity
#define _Included_com_hao_NDKDemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hao_NDKDemoActivity
 * Method:    distance
 * Signature: (Lcom/hao/Point;Lcom/hao/Point;)F
 */
JNIEXPORT jfloat JNICALL Java_com_hao_NDKDemoActivity_distance
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
